# -*- coding: utf-8 -*-
"""Latihan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmsE48s5MmCuWyCLPR7vkdI38K2Bm3Ha
"""

import pandas as pd

df = pd.read_csv('/content/latihan.csv')

df.info()

df.head()

X = df[df.columns[:20]]

y = df['price_range']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)

X = scaler.transform(X)
print(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

clf.score(X_test, y_test)